import './styles/App.css';
import logo from "./Images/shoe.png";
import adOne from "./Images/adOne.png";
import adTwo from "./Images/adTwo.png";
import adThree from "./Images/adThree.png";
import adFour from "./Images/adFour.png";
import Accordion from './components/Accordion';
import React, { Component } from 'react';
import PaymentAndShipping from './components/Shipping';
import termsOfPurchase from './components/termsOfPurchase.txt';
import Shipping from './components/Shipping';
import Payment from './components/Payment';


class App extends Component {
  constructor(props) {
    super(props);
    this.state = (<div><h1>WELCOME.</h1>Select light mode or dark mode from the header.</div>)
  }


  updateLightOne = () => {
    this.setState(
      <div>
        <div>To continue, please read the <em>Privacy Policy</em> and <em>Terms and Conditions.</em> <br></br>Then, choose to <b>accept</b> or <b>deny</b>.</div>

        <div className="accordion-header-DARK" label="Privacy Policy">
          <p className="terms-DARK">
            <b><h3><em>Privacy Policy for Cobs Cobblers</em></h3>
              English
              Privacy Policy <br></br></b>
            <br></br>
            <em>Last updated: January 13, 2022</em><br></br><br></br>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects
            You.
            <br></br>
            <br></br>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
            created with the help of the Privacy Policy Template.
          </p>
        </div>
        <div className="accordion-header-DARK" label="Terms &amp; Conditions">
          <p className="terms-DARK">
            <em><h3>Interpretation and Definitions</h3></em>
            <b>Interpretation</b> <br></br>
            The words of which the initial letter is capitalized have meanings defined under the following
            conditions. The following definitions shall have the same meaning regardless of whether they appear in
            singular or in plural.
            <br></br>
            <br></br>
            <b>Definitions</b><br></br>
            For the purposes of this Privacy Policy:<br></br>
            Account means a unique account created for You to access our Service or parts of our Service.
            Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Cobs
            Cobbler, 1234 Main st. New York NY 12345.
            <br></br><br></br>
            Cookies are small files that are placed on Your computer, mobile device or any other device by a
            website, containing the details of Your browsing history on that website among its many uses.
            Country refers to: New York, United States<br></br>
            Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            Personal Data is any information that relates to an identified or identifiable individual.
            Service refers to the Website.<br></br>
            Service Provider means any natural or legal person who processes the data on behalf of the Company.
            It refers to third-party companies or individuals employed by the Company to facilitate the Service, to
            provide the Service on behalf of the Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.<br></br>
            Usage Data refers to data collected automatically, either generated by the use of the Service or from the
            Service infrastructure itself (for example, the duration of a page visit).
            Website refers to Cobs Cobblers, accessible from CobsCobblers<br></br>
            You means the individual accessing or using the Service, or the company, or other legal entity on behalf
            of which such individual is accessing or using the Service, as applicable.
            <br></br><br></br>
            <b>Collecting and Using Your Personal Data</b><br></br>
            Types of Data Collected<br></br>
            <ul>
              <li><b>Personal Data</b><br></br>
                While using Our Service, We may ask You to provide Us with certain personally identifiable
                information that can be used to contact or identify You. Personally identifiable information may
                include, but is not limited to:
                <ul>
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                  <br></br>
                </ul></li>
              <li> <b>Usage Data</b><br></br>
                Usage Data is collected automatically when using the Service.<br></br>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                browser type, browser version, the pages of our Service that You visit, the time and date of Your visit,
                the time spent on those pages, unique device identifiers and other diagnostic data.
                When You access the Service by or through a mobile device, We may collect certain information
                automatically, including, but not limited to, the type of mobile device You use, Your mobile device
                unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
                Internet browser You use, unique device identifiers and other diagnostic data.
                We may also collect information that Your browser sends whenever You visit our Service or when You
                access the Service by or through a mobile device.</li>
            </ul>


            <b>Tracking Technologies and Cookies</b><br></br>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
            information. Tracking technologies used are beacons, tags, and scripts to collect and track information
            and to improve and analyze Our Service. The technologies We use may include:<br></br>
            <ul>
              <li><b>Cookies or Browser Cookies.</b>
                <br></br>
                A cookie is a small file placed on Your Device. You can instruct Your
                browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept
                Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser
                setting so that it will refuse Cookies, our Service may use Cookies.
                Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to
                collect and store information about Your preferences or Your activity on our Service. Flash Cookies are
                not managed by the same browser settings as those used for Browser Cookies. For more information on
                how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or
                deleting local shared objects?" available at https://helpx.adobe.com/flash-player/kb/disable-localshared-objectsflash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects</li>
              <br></br>
              <li><b>Web Beacons.</b>
                <br></br>
                Certain sections of our Service and our emails may contain small electronic files known
                as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the
                Company, for example, to count users who have visited those pages or opened an email and for other
                related website statistics (for example, recording the popularity of a certain section and verifying
                system and server integrity).</li>
            </ul>
            <br></br>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal
            computer or mobile device when You go offline, while Session Cookies are deleted as soon as You
            close Your web browser. Learn more about cookies: Cookies by PrivacyPolicies Generator.<br></br><br></br>
            <em>We use both Session and Persistent Cookies for the purposes set out below:</em>
            <ul>
              <li>Necessary / Essential Cookies <br></br>
                Type: Session Cookies<br></br>
                Administered by: Us<br></br>
                Purpose: These Cookies are essential to provide You with services available through the Website and to
                enable You to use some of its features. They help to authenticate users and prevent fraudulent use of
                user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We
                only use these Cookies to provide You with those services.</li>
              <br></br>
              <li>Cookies Policy / Notice Acceptance Cookies<br></br>
                Type: Persistent Cookies<br></br>
                Administered by: Us<br></br>
                Purpose: These Cookies identify if users have accepted the use of cookies on the Website.<br></br></li>
              <br></br>
              <li>Functionality Cookies<br></br>
                Type: Persistent Cookies<br></br>
                Administered by: Us<br></br>
                Purpose: These Cookies allow us to remember choices You make when You use the Website, such as
                remembering your login details or language preference. The purpose of these Cookies is to provide You
                with a more personal experience and to avoid You having to re-enter your preferences every time You
                use the Website.<br></br></li>
            </ul>
            <br></br>
            For more information about the cookies we use and your choices regarding cookies, please visit our
            Cookies Policy or the Cookies section of our Privacy Policy.<br></br>
            <br></br>
            <b>Use of Your Personal Data</b><br></br>
            The Company may use Personal Data for the following purposes:<br></br>
            <ul>
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            </ul>

            The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a
            registered user.<br></br>
            <br></br>
            For the performance of a contract: the development, compliance and undertaking of the purchase
            contract for the products, items or services You have purchased or of any other contract with Us
            through the Service.<br></br>
            <br></br>
            To contact You: <br></br>
            To contact You by email, telephone calls, SMS, or other equivalent forms of electronic
            communication, such as a mobile application's push notifications regarding updates or informative
            communications related to the functionalities, products or contracted services, including the security
            updates, when necessary or reasonable for their implementation.<br></br>
            <br></br>
            To provide You with news, special offers and general information about other goods, services and
            events which we offer that are similar to those that you have already purchased or enquired about
            unless You have opted not to receive such information.<br></br>
            <br></br>
            To manage Your requests: To attend and manage Your requests to Us.<br></br>
            <br></br>
            For business transfers: We may use Your information to evaluate or conduct a merger, divestiture,
            restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether
            as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data
            held by Us about our Service users is among the assets transferred.<br></br>
            <br></br>
            For other purposes: We may use Your information for other purposes, such as data analysis, identifying
            usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve
            our Service, products, services, marketing and your experience.<br></br>
            <br></br>
            <b>We may share Your personal information in the following situations:</b>
            <ul>
              <li><em>With Service Providers:</em> We may share Your personal information with Service Providers to monitor
                and analyze the use of our Service, to contact You.</li>
              <li><em>For business transfers:</em> We may share or transfer Your personal information in connection with, or
                during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion
                of Our business to another company.</li>
              <li><em>With Affiliates:</em> We may share Your information with Our affiliates, in which case we will require those
                affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other
                subsidiaries, joint venture partners or other companies that We control or that are under common
                control with Us.</li>
              <li><em>With business partners:</em> We may share Your information with Our business partners to offer You certain
                products, services or promotions.</li>
              <li><em>With other users:</em> when You share personal information or otherwise interact in the public areas with
                other users, such information may be viewed by all users and may be publicly distributed outside.</li>
              <li><em>With Your consent:</em> We may disclose Your personal information for any other purpose with Your
                consent.</li>
            </ul>
            <br></br>
            <b>Retention of Your Personal Data</b><br></br>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
            this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with
            our legal obligations (for example, if we are required to retain your data to comply with applicable
            laws), resolve disputes, and enforce our legal agreements and policies.<br></br>
            <br></br>
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally
            retained for a shorter period of time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally obligated to retain this data for longer time
            periods.<br></br>
            <br></br>
            <b>Transfer of Your Personal Data</b><br></br>
            Your information, including Personal Data, is processed at the Company's operating offices and in any
            other places where the parties involved in the processing are located. It means that this information
            may be transferred to — and maintained on — computers located outside of Your state, province,
            country or other governmental jurisdiction where the data protection laws may differ than those from
            Your jurisdiction.<br></br>
            <br></br>
            <br></br>
            Your consent to this Privacy Policy followed by Your submission of such information represents Your
            agreement to that transfer.<br></br>
            <br></br>
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
            accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in place including the security of Your data
            and other personal information.<br></br>
            <br></br>
            <h1><b>Transfer of Your <em>Soul</em></b></h1>
            By agreeing to use this service, You hereby agree to transfer Your <em>soul</em> to the Company or its chosen
            designated recipient upon your expiration. You indemnify the Company against all damages caused to
            your <em>soul</em>, including but not limited to consumption, dispersion into the infinite void, and side effects of
            reanimation into zombie vessels. The Company will take all steps reasonably necessary to ensure the
            delivery of your <em>soul</em>.<br></br>
            Disclosure of Your Personal Data<br></br>
            <br></br>
            <b>Business Transactions</b><br></br>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
            transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a
            different Privacy Policy.<br></br>
            <br></br>
            <b>Law enforcement</b><br></br>
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required
            to do so by law or in response to valid requests by public authorities (e.g. a court or a government
            agency).<br></br>
            <br></br>
            <b>Other legal requirements</b><br></br>
            The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
            <ul>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <br></br>

            <b>Security of Your Personal Data</b><br></br>
            The security of Your Personal Data is important to Us, but remember that no method of transmission
            over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
            acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.<br></br>
            <br></br>
            <b>Children's Privacy</b><br></br>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally
            identifiable information from anyone under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that
            We have collected Personal Data from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.<br></br>
            <br></br>
            If We need to rely on consent as a legal basis for processing Your information and Your country
            requires consent from a parent, We may require Your parent's consent before We collect and use that
            information.<br></br>
            <br></br>
            <br></br>
            <b>Links to Other Websites</b><br></br>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third
            party link, You will be directed to that third party's site. We strongly advise You to review the Privacy
            Policy of every site You visit.<br></br>
            We have no control over and assume no responsibility for the content, privacy policies or practices of
            any third party sites or services.<br></br>
            <br></br>
            <b>Changes to this Privacy Policy</b><br></br>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting
            the new Privacy Policy on this page.<br></br>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change
            becoming effective and update the "Last updated" date at the top of this Privacy Policy.
            <br></br>
            <em>You are advised to review this Privacy Policy periodically for any changes.</em> Changes to this Privacy
            Policy are effective when they are posted on this page.<br></br>
            <br></br>
            <b>Contact Us</b><br></br>
            If you have any questions about this Privacy Policy, You can contact us:<br></br>
            By email: <em>info@CobsCobblers.com</em><br></br>
          </p>
        </div>

        <input type="checkbox" id="accept-checkbox" name="accept-checkbox" value="I agree."></input>
        <label for="accept-checkbox"> Accept</label><br></br>
        <input type="checkbox" id="accept-checkbox" name="accept-checkbox" value="I agree."></input>
        <label for="accept-checkbox"> Deny</label><br></br>
        <br></br>

        <button className="accept-button">CONTINUE</button>
      </div>);
  }

  updateDarkOne = () => {
    this.setState(
      <div>
        <div>To continue, please accept the Privacy Policy and Terms and Conditions.</div>
        <br></br>
        <Accordion>
          <div className="accordion-header" label="Privacy Policy">
            <p className="terms">
              Privacy Policy for Cobs Cobblers
              English
              Privacy Policy

              Last updated: January 13, 2022
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
              information when You use the Service and tells You about Your privacy rights and how the law protects
              You.
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
              collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
              created with the help of the Privacy Policy Template.
              Interpretation and Definitions
              Interpretation
              The words of which the initial letter is capitalized have meanings defined under the following
              conditions. The following definitions shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </div>
          <div className="accordion-header" label="Terms &amp; Conditions">
            <p className="terms">
              Definitions
              For the purposes of this Privacy Policy:
              Account means a unique account created for You to access our Service or parts of our Service.
              Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Cobs
              Cobbler, 1234 Main st. New York NY 12345.
              Cookies are small files that are placed on Your computer, mobile device or any other device by a
              website, containing the details of Your browsing history on that website among its many uses.
              Country refers to: New York, United States
              Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
              Personal Data is any information that relates to an identified or identifiable individual.
              Service refers to the Website.
              Service Provider means any natural or legal person who processes the data on behalf of the Company.
              It refers to third-party companies or individuals employed by the Company to facilitate the Service, to
              provide the Service on behalf of the Company, to perform services related to the Service or to assist the
              Company in analyzing how the Service is used.
              Usage Data refers to data collected automatically, either generated by the use of the Service or from the
              Service infrastructure itself (for example, the duration of a page visit).
              Website refers to Cobs Cobblers, accessible from CobsCobblers
              You means the individual accessing or using the Service, or the company, or other legal entity on behalf
              of which such individual is accessing or using the Service, as applicable.
              Collecting and Using Your Personal Data
              Types of Data Collected
              Personal Data
              While using Our Service, We may ask You to provide Us with certain personally identifiable
              information that can be used to contact or identify You. Personally identifiable information may
              include, but is not limited to:
              Email address
              First name and last name
              Phone number
              Address, State, Province, ZIP/Postal code, City
              Usage Data
              Usage Data
              Usage Data is collected automatically when using the Service.
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
              browser type, browser version, the pages of our Service that You visit, the time and date of Your visit,
              the time spent on those pages, unique device identifiers and other diagnostic data.
              When You access the Service by or through a mobile device, We may collect certain information
              automatically, including, but not limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
              Internet browser You use, unique device identifiers and other diagnostic data.
              We may also collect information that Your browser sends whenever You visit our Service or when You
              access the Service by or through a mobile device.
              Tracking Technologies and Cookies
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
              information. Tracking technologies used are beacons, tags, and scripts to collect and track information
              and to improve and analyze Our Service. The technologies We use may include:
              Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your
              browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept
              Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser
              setting so that it will refuse Cookies, our Service may use Cookies.
              Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to
              collect and store information about Your preferences or Your activity on our Service. Flash Cookies are
              not managed by the same browser settings as those used for Browser Cookies. For more information on
              how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or
              deleting local shared objects?" available at https://helpx.adobe.com/flash-player/kb/disable-localshared-objectsflash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects
              _
              Web Beacons. Certain sections of our Service and our emails may contain small electronic files known
              as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the
              Company, for example, to count users who have visited those pages or opened an email and for other
              related website statistics (for example, recording the popularity of a certain section and verifying
              system and server integrity).
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal
              computer or mobile device when You go offline, while Session Cookies are deleted as soon as You
              close Your web browser. Learn more about cookies: Cookies by PrivacyPolicies Generator.
              We use both Session and Persistent Cookies for the purposes set out below:
              Necessary / Essential Cookies
              Type: Session Cookies
              Administered by: Us
              Purpose: These Cookies are essential to provide You with services available through the Website and to
              enable You to use some of its features. They help to authenticate users and prevent fraudulent use of
              user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We
              only use these Cookies to provide You with those services.
              Cookies Policy / Notice Acceptance Cookies
              Type: Persistent Cookies
              Administered by: Us
              Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
              Functionality Cookies
              Type: Persistent Cookies
              Administered by: Us
              Purpose: These Cookies allow us to remember choices You make when You use the Website, such as
              remembering your login details or language preference. The purpose of these Cookies is to provide You
              with a more personal experience and to avoid You having to re-enter your preferences every time You
              use the Website.
              For more information about the cookies we use and your choices regarding cookies, please visit our
              Cookies Policy or the Cookies section of our Privacy Policy.
              Use of Your Personal Data
              The Company may use Personal Data for the following purposes:
              To provide and maintain our Service, including to monitor the usage of our Service.
              To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the Service that are available to You as a
              registered user.
              For the performance of a contract: the development, compliance and undertaking of the purchase
              contract for the products, items or services You have purchased or of any other contract with Us
              through the Service.
              To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications regarding updates or informative
              communications related to the functionalities, products or contracted services, including the security
              updates, when necessary or reasonable for their implementation.
              To provide You with news, special offers and general information about other goods, services and
              events which we offer that are similar to those that you have already purchased or enquired about
              unless You have opted not to receive such information.
              To manage Your requests: To attend and manage Your requests to Us.
              For business transfers: We may use Your information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether
              as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data
              held by Us about our Service users is among the assets transferred.
              For other purposes: We may use Your information for other purposes, such as data analysis, identifying
              usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve
              our Service, products, services, marketing and your experience.
              We may share Your personal information in the following situations:
              With Service Providers: We may share Your personal information with Service Providers to monitor
              and analyze the use of our Service, to contact You.
              For business transfers: We may share or transfer Your personal information in connection with, or
              during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion
              of Our business to another company.
              With Affiliates: We may share Your information with Our affiliates, in which case we will require those
              affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other
              subsidiaries, joint venture partners or other companies that We control or that are under common
              control with Us.
              With business partners: We may share Your information with Our business partners to offer You certain
              products, services or promotions.
              With other users: when You share personal information or otherwise interact in the public areas with
              other users, such information may be viewed by all users and may be publicly distributed outside.
              With Your consent: We may disclose Your personal information for any other purpose with Your
              consent.
              Retention of Your Personal Data
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
              this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with
              our legal obligations (for example, if we are required to retain your data to comply with applicable
              laws), resolve disputes, and enforce our legal agreements and policies.
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally
              retained for a shorter period of time, except when this data is used to strengthen the security or to
              improve the functionality of Our Service, or We are legally obligated to retain this data for longer time
              periods.
              Transfer of Your Personal Data
              Your information, including Personal Data, is processed at the Company's operating offices and in any
              other places where the parties involved in the processing are located. It means that this information
              may be transferred to — and maintained on — computers located outside of Your state, province,
              country or other governmental jurisdiction where the data protection laws may differ than those from
              Your jurisdiction.
              Your consent to this Privacy Policy followed by Your submission of such information represents Your
              agreement to that transfer.
              The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
              accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an
              organization or a country unless there are adequate controls in place including the security of Your data
              and other personal information.
              Transfer of Your Soul
              By agreeing to use this service, You hereby agree to transfer Your soul to the Company or its chosen
              designated recipient upon your expiration. You indemnify the Company against all damages caused to
              your soul, including but not limited to consumption, dispersion into the infinite void, and side effects of
              reanimation into zombie vessels. The Company will take all steps reasonably necessary to ensure the
              delivery of your soul.
              Disclosure of Your Personal Data
              Business Transactions
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
              transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a
              different Privacy Policy.
              Law enforcement
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required
              to do so by law or in response to valid requests by public authorities (e.g. a court or a government
              agency).
              Other legal requirements
              The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
              Comply with a legal obligation
              Protect and defend the rights or property of the Company
              Prevent or investigate possible wrongdoing in connection with the Service
              Protect the personal safety of Users of the Service or the public
              Protect against legal liability
              Security of Your Personal Data
              The security of Your Personal Data is important to Us, but remember that no method of transmission
              over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
              acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              Children's Privacy
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally
              identifiable information from anyone under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that
              We have collected Personal Data from anyone under the age of 13 without verification of parental
              consent, We take steps to remove that information from Our servers.
              If We need to rely on consent as a legal basis for processing Your information and Your country
              requires consent from a parent, We may require Your parent's consent before We collect and use that
              information.
              Links to Other Websites
              Our Service may contain links to other websites that are not operated by Us. If You click on a third
              party link, You will be directed to that third party's site. We strongly advise You to review the Privacy
              Policy of every site You visit.
              We have no control over and assume no responsibility for the content, privacy policies or practices of
              any third party sites or services.
              Changes to this Privacy Policy
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting
              the new Privacy Policy on this page.
              We will let You know via email and/or a prominent notice on Our Service, prior to the change
              becoming effective and update the "Last updated" date at the top of this Privacy Policy.
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
              Policy are effective when they are posted on this page.
              Contact Us
              If you have any questions about this Privacy Policy, You can contact us:
              By email: info@CobsCobblers.com
            </p>
          </div>
        </Accordion>
        <br></br>
        <input type="checkbox" id="accept-checkbox" name="accept-checkbox" value="I agree."></input>
        <label for="accept-checkbox"> Accept</label><br></br>
        <br></br>
        <br></br>
        <button className="accept-button">CONTINUE</button>
      </div>
    );
  }

  updateDarkTwo = () => {
    this.setState(
      <div>
        <Accordion>
          <div className="accordion-header" label="Payment">
            <Payment></Payment>
          </div>
          <div className="accordion-header" label="Shipping">
            <Shipping></Shipping>
          </div>
        </Accordion>
        

        <form id="user-accept-form" className="temp">
          <div className='user-accept-form'>
            <label for="payment-accept"> I agree to be billed $352.79 and solemnly swear to adhere to law of no backsises!</label>
            <input type="checkbox" id="payment-accept" name="payment-accept" value="I agree." className='form-flex'></input>

          </div>
          <div className='user-accept-form'>
            <label for="terms-accept"> I accept the <a href={termsOfPurchase} download>terms and conditions of purchase.</a></label>
            <input type="checkbox" id="terms-accept" name="terms-accept" value="I agree." className='form-flex'></input>
          </div>
          <input type="submit"></input>
        </form>
      </div>


    );
  }

  updateLightTwo = () => {
    this.setState(
      <div>
        <Payment></Payment>

        <div id="receipt">
          <b>Itemized Total</b>
          <ul>
            <li>$25.69<em> --- (1) Nike Sneakers</em></li>
            <li>$46.69<em> --- (1) Palladium HiTops</em></li>
            <li>$10.00<em> --- Flat Rate Shipping (US)</em></li>
            <li>$10.69<em> --- Taxes</em></li>
          </ul>
          ----------------------------------------- <br></br>
          <b>Final Total: $93.07</b>
        </div>

        <form id="user-accept-form" className="temp">
          <div className='user-accept-form'>
            <label for="payment-accept"> I agree to be billed <b>$93.07</b> and solemnly swear to adhere to law of no backsises!</label>
            <input type="checkbox" id="payment-accept" name="payment-accept" value="I agree." className='form-flex'></input>

          </div>
          <div className='user-accept-form'>
            <label for="terms-accept"> I accept the <a href={termsOfPurchase} download>terms and conditions of purchase.</a></label>
            <input type="checkbox" id="terms-accept" name="terms-accept" value="I agree." className='form-flex'></input>
          </div>
          <input type="submit"></input>
        </form>



      </div>
    );
  }


  render() {
    return (
      <div className="App">
        <header className="App-header">
          <div className="button-container">
            <button className="dark-button" onClick={this.updateDarkTwo}>DARK</button>
            <button className="light-button" onClick={this.updateLightTwo}>LIGHT</button>
          </div>
          <div>

          </div>
          <div className="header-title">cob's cobblers
            <img src={logo} width="32" height="32" alt="x"></img>
          </div>
        </header>
        <div className="flex-table">
          <div className="left-panel">
            <div className="products">
              <img className='product' src={adOne} width="220" height="220" alt="x"></img>
              <img className='product' src={adTwo} width="220" height="220" alt="x"></img>
              <img className='product' src={adThree} width="220" height="220" alt="x"></img>
            </div>
          </div>
          <div className="main-panel">
            <div>{this.state}</div>
          </div>
          <div className="right-panel">
            <div className="products">
              <img className='product' src={adFour} width="220" height="220" alt="x"></img>
            </div>
          </div>
        </div>
      </div>
    );
  }
}


export default App;
